# Usecase-5:
# Create a Docker Compose File for setting up the Testing Environment.
# Where a Selinium Hub Container should be Linked with 2 Node Containers
# 1) Firefox 2) Chrome.
---
version: '3'

services:
 hub:
  image: selenium/hub
  ports:
   - 4444:4444

 chrome:
  image: selenium/node-chrome-debug
  ports:
   - 5901:5900
  links:
   - hub:selenium

 firefox:
  image: selenium/node-firefox-debug
  ports:
   - 5902:5900
  links:
   - hub:selenium




...
